export enum WALLET_ACTION_TYPES {
  GET_NUBAN_ACCOUNTS_ERROR = 'wallet/GET_NUBAN_ACCOUNTS_ERROR',
  GET_NUBAN_ACCOUNTS_REQUEST = 'wallet/GET_NUBAN_ACCOUNTS_REQUEST',
  GET_NUBAN_ACCOUNTS_SUCCESS = 'wallet/GET_NUBAN_ACCOUNTS_SUCCESS',

  GET_USER_CRYPTO_ADDRESS_ERROR = 'wallet/GET_USER_CRYPTO_ADDRESS_ERROR',
  GET_USER_CRYPTO_ADDRESS_REQUEST = 'wallet/GET_USER_CRYPTO_ADDRESS_REQUEST',
  GET_USER_CRYPTO_ADDRESS_SUCCESS = 'wallet/GET_USER_CRYPTO_ADDRESS_SUCCESS',

  GET_USER_WALLET_ERROR = 'wallet/GET_USER_WALLET_ERROR',
  GET_USER_WALLET_REQUEST = 'wallet/GET_USER_WALLET_REQUEST',
  GET_USER_WALLET_SUCCESS = 'wallet/GET_USER_WALLET_SUCCESS',

  SEND_MONEY_TO_USER_ERROR = 'wallet/SEND_MONEY_TO_USER_ERROR',
  SEND_MONEY_TO_USER_REQUEST = 'wallet/SEND_MONEY_TO_USER_REQUEST',
  SEND_MONEY_TO_USER_SUCCESS = 'wallet/SEND_MONEY_TO_USER_SUCCESS',

  TOGGLE_TOTAL_BALANCE_VISIBILITY = 'wallet/TOGGLE_TOTAL_BALANCE_VISIBILITY',
  TOGGLE_WALLET_BALANCE_VISIBILITY = 'wallet/TOGGLE_WALLET_BALANCE_VISIBILITY',
  WITHDRAW_TO_WALLET_FROM_PLAN_ERROR = 'wallet/WITHDRAW_TO_WALLET_FROM_PLAN_ERROR',

  WITHDRAW_TO_WALLET_FROM_PLAN_REQUEST = 'wallet/WITHDRAW_TO_WALLET_FROM_PLAN_REQUEST',
  WITHDRAW_TO_WALLET_FROM_PLAN_SUCCESS = 'wallet/WITHDRAW_TO_WALLET_FROM_PLAN_SUCCESS'
}

export type FetchWalletSuccess = {
  type: WALLET_ACTION_TYPES.GET_USER_WALLET_SUCCESS
  wallet: IRiseWallet
}

export type FetchCryptoAddressSuccess = {
  cryptoAddress: string
  type: WALLET_ACTION_TYPES.GET_USER_CRYPTO_ADDRESS_SUCCESS
}

export type WithdrawToWalletSuccess = {
  amount: number
  hasMatured: boolean
  type: WALLET_ACTION_TYPES.WITHDRAW_TO_WALLET_FROM_PLAN_SUCCESS
}

export type SetWalletVisibility = {
  isVisible: boolean
  type: WALLET_ACTION_TYPES.TOGGLE_WALLET_BALANCE_VISIBILITY
}

export type SetTotalBalanceVisibility = {
  isVisible: boolean
  type: WALLET_ACTION_TYPES.TOGGLE_TOTAL_BALANCE_VISIBILITY
}

export type FetchNubanBankAccountsSuccess = {
  accounts: IRiseWallet[]
  type: WALLET_ACTION_TYPES.GET_NUBAN_ACCOUNTS_SUCCESS
}

export type WalletActions =
  | FetchWalletSuccess
  | SetWalletVisibility
  | SetTotalBalanceVisibility
  | FetchNubanBankAccountsSuccess
